name: Release
run-name: ${{ github.actor }} is creating a draft release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended librsvg2-bin zip
    - name: Convert Readme.md to PDF
      run: |
        rsvg-convert -f pdf -o README.pdf README.svg
    - name: Archive WaterInteractionPlugin folder + Readme.pdf + LICENSE file
      run: |
        zip -r WaterInteractionPlugin.zip WaterInteractionPlugin README.pdf LICENSE
    - name: Get the latest release tag and increment it
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags --abbrev=0)
        IFS='.' read -ra ver <<< "$latest_tag"
        new_tag="${ver[0]}.${ver[1]}.$((${ver[2]}+1))"
        git tag "$new_tag"
        echo "$new_tag"
        export VERSION="$new_tag"
    - name: Create Release Draft
      uses: actions/create-release-draft@v1
      with:
        tag_name: ${{ env.VERSION }}
        draft: true
    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: WaterInteractionPlugin-$VERSION-$GITHUB_SHA.zip
        asset_name: WaterInteractionPlugin-$VERSION-$GITHUB_SHA.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
