name: Create Release Draft
run-name: ${{ github.actor }} is creating a draft release
on:
  push:
    branches:
      - main
jobs:
  create_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: Sartaq12/WaterInteractionPlugin  # The repository to scan.
        releases-only: false # We know that all relevant tags have a GitHub release for them.
      id: WaterInteractionPlugin  # The step ID to refer to later.
    - run: echo "WaterInteractionPlugin is at version ${{ steps.WaterInteractionPlugin.outputs.tag }}"
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended pandoc zip
    - name: Convert Readme.md to PDF
      run: |
        pandoc README.md -o README.pdf
    - name: Get Latest Tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
  
    - name: Archive WaterInteractionPlugin folder + Readme.pdf + LICENSE file
      run: |
        zip -r WaterInteractionPlugin-${{ steps.WaterInteractionPlugin.outputs.tag }}.zip WaterInteractionPlugin README.pdf LICENSE && rm README.pdf
    - name: Create Release Draft
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.WaterInteractionPlugin.outputs.tag }}
        release_name: Release-${{ steps.WaterInteractionPlugin.outputs.tag }}
        draft: true
        prerelease: false
    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: WaterInteractionPlugin-${{ steps.WaterInteractionPlugin.outputs.tag }}.zip
        asset_name: WaterInteractionPlugin-${{ steps.WaterInteractionPlugin.outputs.tag }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Release
      uses: actions/create-release@v1.1.4
      with:
        tag_name: ${{ steps.WaterInteractionPlugin.outputs.tag }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
