name: Release
run-name: ${{ github.actor }} is creating a draft release
on:
  push:
    branches:
      - main

env:
  FILENAME: WaterInteractionPlugin
  VERSION: $(git describe --tags --abbrev=0)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            zip \
            pandoc \
            texlive-xetex

      - name: Convert README to PDF
        run: pandoc -o README.pdf README.md

      - name: Zip files
        run: zip -r "$FILENAME-$(git describe --tags --abbrev=0)-${GITHUB_SHA::8}.zip" "$FILENAME" README.pdf && rm README.pdf

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.FILENAME }}-${{ env.VERSION }}-${{ github.sha }}.zip
          asset_name: ${{ env.FILENAME }}-${{ env.VERSION }}-${{ github.sha }}.zip
          asset_content_type: application/zip

      - name: Update Release Draft
        uses: peter-evans/create-pull-request@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'Update Release Draft'
          branch: update-release-draft
          title: 'Update Release Draft'
          body: |
            - Update release draft
          base: main
          head: update-release-draft
          draft: true
          delete-branch: true
